### ISSUE TITLE
Cant get secret key

### ISSUE THREAD

**Issue by morb14** [call-042PE/Mephistopheles#1]
Can you help me fine the secret key for this program?
https://cracked.to/Thread-Supreme-Flawless-LoL-Console-Cracker-Config-system-Email-access-10k-CPM-Insane
i cant seem to bypass at all

**Comment by call-042PE** [comment]
This program doesn't support the new cracked.to auth all you have to do is to click on start.

**Comment by morb14** [comment]
`                         ______ __                  __
                        / ____// /____ _ _      __ / /___   _____ _____
                       / /_   / // __ `/| | /| / // // _ \ / ___// ___/
                      / __/  / // /_/ / | |/ |/ // //  __/(__  )(__  )
                     /_/    /_/ \__,_/  |__/|__//_/ \___//____//____/

                                   [ Flawless - v.1.0.0 ]
                                  18:59, Kekd {Cracked.To}

[18:59:38] | Enter your cracked.to key: f

Unhandled Exception: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
--- End of stack trace from previous location where exception was thrown ---
   at (Exception )
   at ?.(Exception )
   at (? , Object )
   at ?.(Object )
   at (? , MethodBase , Boolean )
   at ?.(MethodBase , Boolean )
   at (? ,   )
   at ?.(  )
   at (? ,   )
   at ?.  (? ,   )
   at (? )
   at ?()
   at (? , Boolean )
--- End of stack trace from previous location where exception was thrown ---
   at (Exception )
   at ?.(Exception )
   at (? , Object )
   at ?.(Object )
   at (? )
   at ?.()
   at (? , Object , UInt32 )
   at ?.(Object , UInt32 )
   at (? , Boolean )
   at ?.(Boolean )
   at (? )
   at ?.()
   at (? , Object[] , Type[] , Type[] , Object[] )
   at ?.(Object[] , Type[] , Type[] , Object[])
   at (? , Stream , String , Object[] , Type[] , Type[] , Object[] )
   at ?.(Stream , String , Object[] , Type[], Type[] , Object[] )
   at (? , Stream , String , Object[] )
   at ?.(Stream , String , Object[] )
   at (? , Stream , String , Object[] )
   at ?.(Stream , String , Object[] )
   at ()
   at  ()
`
This is what i get

**Comment by call-042PE** [comment]
You have to install the server.crt

**Comment by mert1291** [comment]
I get the same error, even though I installed the certificate

**Comment by call-042PE** [comment]
Did you installed it in trusted root certification authorities ?

**Comment by mert1291** [comment]
yes

**Comment by call-042PE** [comment]
You have to install python3 and make sure it's added to the path
